--REVENUE ANALYSIS
-- What is the total revenue for each product category?
select distinct product_category, sum(quantity) AS total_quantity, sum(total_amount) as total_revenue
from sales_data
group by  product_category
order by total_revenue desc

--GENDER INSIGHTS
--Total revenue generated by each gender
select gender, sum(total_amount) as total_revenue
from sales_data 
group by gender
order by total_revenue desc

--Total revenue generated by each gender in all product categories
select product_category,gender, sum(total_amount) as total_revenue
from sales_data 
group by product_category, gender
order by product_category, total_revenue desc

--AGE DEMOGRAPHIC INSIGHTS
--Revenue and quantities sold based on age groups
with AgeGroup as (
select case
	when age between 18 and 24 then '18-24'
	when age between 25 and 34 then '25-34'
	when age between 35 and 44 then '35-44'
	when age between 45 and 54 then '45-54'
	when age between 55 and 64 then '55-64'
	when age >= 65 then '65+'
end as age_group,total_amount, quantity, transaction_id
from sales_data
)
select age_group, count(distinct transaction_id) as total_transactions,  sum(quantity) as total_quantity, sum(total_amount) as total_revenue, sum(total_amount)/count(distinct transaction_id) as avg_order_value
from AgeGroup
group by age_group
order by total_revenue desc

--INVENTORY/PRODUCT INSIGHTS
--Seasonal trends in product sales
with MonthTotals as (
select  order_month, count(distinct transaction_id) as total_transactions, sum(total_amount) as total_revenue
from sales_data
group by order_month
)
select order_month, total_transactions,total_revenue, total_revenue / total_transactions as avg_order_value
from MonthTotals
order by total_revenue desc